# This user will be created on nextcloud host and the backups host
# it will be in charge of all operations.
backup_user: nextsavior

# This is nextcloud's hostname from the point of vue of the backup
# host (you can enter an ip address).
nextcloud_host: nextcloud.lab

# This is nextcloud's default credentials for its database, you
# must change the password accordingly.
database:
  name: nextcloud
  user: oc_admin
  password: k6wvf+vqhqlwT9zXS9oLXA0X+l9Imm
