- name: user nextsavior is present
  user:
    name: "{{ backup_user }}"
    state: present
    shell: /usr/sbin/nologin

- name: "ssh directory exist in {{ backup_user }}'s home"
  file:
    path: "/home/{{ backup_user }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ backup_user }}"
    group: "{{ backup_user }}"

- name: add ssh keys
  copy:
    src: "{{ item.src }}"
    dest: "/home/{{ backup_user }}/.ssh/{{ item.src }}"
    owner: "{{ backup_user }}"
    group: "{{ backup_user }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: 'id_rsa', mode: '600' }
    - { src: 'id_rsa.pub', mode: '644' }

- name: ssh keys are generated for nextcloud hosts
  command: "ssh-keyscan -t rsa {{ nextcloud_host }}"
  register: ssh_host_key

- name: backup host know nextcloud host
  become_user: "{{ backup_user }}"
  known_hosts:
    path: "/home/{{ backup_user }}/.ssh/known_hosts"
    name: "{{ nextcloud_host }}"
    key: "{{ ssh_host_key.stdout }}"

- name: backup script is present
  template:
    src: backup.sh
    dest: "/home/{{ backup_user }}/"
    owner: "{{ backup_user }}"
    group: "{{ backup_user }}"
    mode: 0500

- name: "{{ backup_user }} has rights on /data/backup"
  file:
    path: "/data/backup/"
    state: directory
    mode: 0700
    owner: "{{ backup_user }}"
